### ISSUE TITLE
This is great

### ISSUE THREAD

**Issue by PJ-Finlay** [uav4geo/LibreTranslate#1]
This looks really cool! Let me know when the web demo is stable enough and I'll link it from the Argos Translate README.

**Comment by pierotofy** [comment]
Hey @PJ-Finlay  :hand: I was about to message you later tomorrow (I'm still battling some issues with the server setup) to let you know about the project!

My short term goal is to create an addition to the Discourse translate plugin (https://github.com/discourse/discourse-translator) and add support for this API/Argo, which will be useful to the OpenDroneMap community at https://community.opendronemap.org.

But I think the applications for a FOSS machine translation solution are far and wide. Would love to connect sometimes to chat about it. :+1:

**Comment by PJ-Finlay** [comment]
Sounds great! It seems like you know what you're doing but let me know if you need support/information about Argos Translate. If you want to chat email me at the admin@argosopentech.com email listed on the website. Also if there are specific languages you need let me know, I'm still in the process of training language models. You mentioned in the README you wanted language detection, I'm hoping to add this at some point and can probably use the existing translation code for it but I'm waiting to train more language models before I train a detection model.
