### ISSUE TITLE
Japanese Translation Support?

### ISSUE THREAD

**Issue by ThisNekoGuy** [uav4geo/LibreTranslate#18]
Would like to see Japanese be a supported language at some point! :smiley:

**Comment by pierotofy** [comment]
Excellent idea! Perhaps you could help us train a Japanese model @ThisNekoGuy ?

See https://github.com/argosopentech/onmt-models

**Comment by PJ-Finlay** [comment]
Related: https://github.com/argosopentech/argos-translate/issues/25

**Comment by ThisNekoGuy** [comment]
@pierotofy Unfortunately, I'm not well versed in Japanese myself to do so (which to my understand may be a requirement here?)...
I just happened to see LibreTranslate as an alternative to Google and jumped :laughing: 

If that's not required though, I might be able to help? I've never done that before but I do have an Nvidia GPU but I run an Arch Linux derivative, not Debian or Ubuntu

**Comment by PJ-Finlay** [comment]
You should be able to run the training scripts on your computer. The hardest part will be manually collecting the data and getting Nvidia drivers installed. If you're interested on training a Japanese model I could upload it with the rest of the models. No knowledge of Japanese required.

**Comment by ThisNekoGuy** [comment]
Alright!
I already have Nvidia drivers installed, by the way (I play games with Wine
on Linux) so that shouldn't be a problem?

**Comment by PJ-Finlay** [comment]
Don't think so, you should be able to follow the Readme in the training script readme

**Comment by ThisNekoGuy** [comment]
Sorry, I know it's been a while.
Trying to get this set up and I wanted to know if it's fine setting up the environment for it on my user system?
What I mean is, I play games on this desktop, I don't usually user it as a server unless I'm doing web development :p
(I'm a junior dev)

**Comment by PJ-Finlay** [comment]
Hi, I'm just finishing a Japanese model which should be available soon but help training other languages would be appreciated. I just finished porting [the training scripts](https://github.com/argosopentech/onmt-models) to OpenNMT-py and documented them. I would try running the demo first. The training scripts install a lot so if you're doing it on your desktop you might want to use a Docker container. Let me know if you have any questions.

For the Python requirements install it's `pip3 install -r requirements.txt`. The `setup.sh` script should do this automatically.

**Comment by ThisNekoGuy** [comment]
Never used Docker, so I'm not quite sure how to respond to that...
I set up a virtual environment for setting up OpenNMT-py but it fails to install the dependencies every time I try

Do you mean that the setup.sh from the model repository itself does all the setup including the OpenNMT-py dependencies?

**Comment by PJ-Finlay** [comment]
`setup.sh` installs everything except OpenNMT-py which gets installed from source. The training scripts aren't as polished as the main Argos Translate repo so you're probably going to have to do some debugging. I just improved the documentation though and can help. Docker isn't necessary but the scripts were designed to be run on a server and install a lot of things you might not want on your desktop. If you just pay attention to what you're installing you should be fine.

**Comment by PJ-Finlay** [comment]
The Japanese models are live on the package index so @pierotofy feel free to close this. @ThisNekoGuy if you need support for the training scripts make a ticket or forum post on the main Argos Translate repo or the training scripts repo.

**Comment by pierotofy** [comment]
That's awesome, thanks @PJ-Finlay :+1:

**Comment by pierotofy** [comment]
Updated the server on https://libretranslate.com with latest models / engine version.

**Comment by saeed-neorelm** [comment]
appreciate the effort, but to be honest the quality is too low
https://libretranslate.com/?source=ja&target=en&q=%E3%81%82%E3%81%AE%E7%94%B7%E3%81%AE%E4%BA%BA%E3%81%AF%E5%8F%8B%E9%81%94%E3%81%A7%E3%80%81%E5%8D%B1%E3%81%AA%E3%81%8F%E3%81%AA%E3%81%84%E3%82%88%E3%80%82

![Image](https://github.com/user-attachments/assets/9a319262-de6b-4991-aa9b-33f6eb1a3253)

**Comment by DealsBeam** [comment]
Hello, I am also interested in Japanese to English translation, as the poster said above the quality is not low - it just needs to be adjusted, for example - it shows the correct translation in the 'Reponse' section:

“That man is a friend, so he’s not dangerous.”

"The man is a friend, he is not dangerous。"

<img width="1298" height="886" alt="Image" src="https://github.com/user-attachments/assets/04c8ccb9-685b-4a6b-bd4c-879429504d0c" />

Will it be updated and adjusted in the future?

**Comment by saeed-neorelm** [comment]
good to know. I wonder what's causing the alternatives to offer better translations. perhaps some bad metadata in the training dataset?
