### ISSUE TITLE
contribution

### ISSUE THREAD

**Issue by menachem-dev** [uav4geo/LibreTranslate#2]
Hey, this looks like a really cool project, how am I able to contribute to the translation aspect, (I am very much not a programmer)?

**Comment by pierotofy** [comment]
Hey @menachem-dev :hand: improving the translation engine is a matter of training better models (see https://github.com/argosopentech/onmt-models ). In absence of code contributions, we'd love if you could simply spread the word out, star us on GitHub or improve the documentation, README, etc. in any way you find useful. :+1: 

@PJ-Finlay might have other suggestions also perhaps.

**Comment by PJ-Finlay** [comment]
@menachem-dev glad your interested in helping! Now that the project has more attention I just wrote some GitHub issues for people interested in helping. I'll try to mark some of them as "Good First Issues". If you don't have that much programming experience I would probably look at either the model distribution or code formatting issue.

**Comment by o-data** [comment]
Hi PJ, where are these issues you mentioned? I don't see any created by you (as author)
