### ISSUE TITLE
Batch translation

### ISSUE THREAD

**Issue by caugner** [uav4geo/LibreTranslate#21]
It would be very nice if the `translate` endpoint would accept multiple texts (or `q`s) at once, like DeepL does.

This should significantly improve the translation performance.

* If `q` is a string, translate it, and return the translation as a string.
* If `q` is an array (list of strings), translate each item, and return the translations as an array (list of strings).

Note that DeepL has a limit of 50 texts per requests, which could be an argument like `--char-limit` (e.g. `--text-limit` or `--q-limit`).

![grafik](https://user-images.githubusercontent.com/495429/105058193-3c586980-5a76-11eb-93a5-577883d90ed0.png)
(Source: https://www.deepl.com/docs-api/translating-text/request/)

**Comment by pierotofy** [comment]
Hey @caugner :hand: I think this is a great idea. Would you be interested in contributing a PR for this?

**Comment by caugner** [comment]
@pierotofy Sure, see #22.

**Comment by caugner** [comment]
(Unfortunately it didn't improve the performance significantly versus requesting each text separately.)
