### ISSUE TITLE
Feature request: Offline mode

### ISSUE THREAD

**Issue by inglesuniversal** [uav4geo/LibreTranslate#27]
Hi, I work a lot with ESL Students and sometimes at their school the internet connection is not up to speed or availability.

Is there a way to have a translation app (English / Spanish) pre-downloaded into their device or hybrid app and being able to display the results to the user.

Thanks

**Comment by pierotofy** [comment]
Hey @inglesuniversal :hand: I think your use case might be best served by https://github.com/argosopentech/argos-translate which offers a offline UI.

**Comment by wuniversales** [comment]
That's fine, but I think it would be very useful to use freetranslate as a offline webapp.
:D

**Comment by pierotofy** [comment]
It would be cool! But I don't think it's possible (you would have to compile/port argos-translate to Javascript).
