### ISSUE TITLE
Astian Translate

### ISSUE THREAD

**Issue by PJ-Finlay** [uav4geo/LibreTranslate#28]
Just making sure you saw: https://astian.org/en/astian-translate-free-and-open-source-translations/

I made a [wiki page](https://github.com/argosopentech/argos-translate/wiki/Projects-using-Argos-Translate) to track projects using Argos Translate. I think this and the corresponding article I linked to were the source of the uptick in traffic the last few days.

**Comment by pierotofy** [comment]
Thanks for sharing the link! Very cool.
