### ISSUE TITLE
Avoid the error "Slowdown: 20 per 1 minute"

### ISSUE THREAD

**Issue by wuniversales** [uav4geo/LibreTranslate#29]
I propose to avoid this by waiting 1 second to translate the text.

That is, when the user stops typing for 1 second, perform the translation automatically.

**Comment by PJ-Finlay** [comment]
Related, caching by paragraphs split on new lines was super easy and gave big performance gains for long translations in the Argos Translate desktop app. Not sure if it would matter as much when you're already going over the network though.

https://github.com/argosopentech/argos-translate/blob/761f2b67e488a8b4c1a9f83e88557b2aa0fc42b1/argostranslate/translate.py#L157-L193

**Comment by pierotofy** [comment]
We already do this, but we currently use 300 milliseconds as a delay (perhaps it's too low?) See https://github.com/uav4geo/LibreTranslate/blob/main/app/templates/index.html#L444

**Comment by worldworm** [comment]
I had problems with this as well. I would love to attach this delay to a new arguments/parameter.
500ms as a default?
What do you think?

**Comment by pierotofy** [comment]
Sounds good to me! You can use the template syntax to make that parameter dynamic.
