### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by edvilme** [uav4geo/LibreTranslate#33]
Hello! I enjoy using this service very much! Congrats and thanks to the community :D

I have noticed that emoji are parsed into the text and was wondering if there was a way to escape \uXXXX (unicode for emoji), treating them as proper nouns as to preserve them? 
I would like to do any type of contribution but wanted to make sure if it is currently possible before messing around with the code. 

Thanks in advance

**Comment by pierotofy** [comment]
Hey @edvilme :hand: that would be a cool addition. I haven't experimented with emojis much, but I would assume it's probably possible to make it work (like you say, by escaping them into nouns).

This might be better suited as a PR for https://github.com/argosopentech/argos-translate though, since it's the translation engine.

**Comment by PJ-Finlay** [comment]
Done, good idea! 

https://github.com/argosopentech/argos-translate/commit/6a0f389caccd35645049f00658636b5c007b98a8

**Comment by pierotofy** [comment]
w00t, that's awesome!

**Comment by edvilme** [comment]
Wait what? OMG awesomeee!

**Comment by pierotofy** [comment]
![image](https://user-images.githubusercontent.com/1951843/107273889-adf45980-6a1d-11eb-922c-c47c05b0e379.png)

This can be closed!

**Comment by graysuit** [comment]
Hi guys,
It looks unstable.

It fails. 
Sometime it remove some emoji from text.
Sometime it replace emoji with some other text.

Its telegram emoji that I used in pic. ✅
![Capture](https://user-images.githubusercontent.com/54432616/115430921-37928580-a21e-11eb-90df-bc312d93ce86.PNG)

**Comment by PJ-Finlay** [comment]
https://github.com/argosopentech/argos-translate/issues/77

**Comment by graysuit** [comment]
It mean it fixed in code but NOT fixed yet on api ?

**Comment by PJ-Finlay** [comment]
It's fixed in the code that processes the data for training models but the Spanish model hasn't been retrained since this fix was made.
