### ISSUE TITLE
[Bug] Do not allow to translate into auto detect language

### ISSUE THREAD

**Issue by wuniversales** [uav4geo/LibreTranslate#44]
Not only do you have to remove that option in the drop-down, you also have to allow clicking on the "swap_horiz" button if the current language is set to Auto detect.

**Comment by pierotofy** [comment]
Fixed in https://github.com/uav4geo/LibreTranslate/commit/90de8e22a04cd68e9f7c37e96c59c2514266141e

Thanks for the report!
