### ISSUE TITLE
[FR] Limit to two languages

### ISSUE THREAD

**Issue by sigaloid** [uav4geo/LibreTranslate#51]
It crashed my 1GB vm when I scrolled through the dropdown languages, I assume it had to load all the language models and process them at once. The API already supports `/languages` but I was unable to find anywhere to limit to a single model. Thanks!

**Comment by pierotofy** [comment]
We don't have such a feature, although it would be a cool addition (interested in cotributing a pull request?)

**Comment by sigaloid** [comment]
I'll try my hand. How should I pass into init.py? An easy way would just be an env variable "LIBRE_LANG_1" and "LIBRE_LANG_2" then check each model to see if it contains both of them. But that might not be considered good form. Maybe I could pass two strings through `check_and_install_models` -> `boot` -> `create_app` -> `main.py` as an argument?

First I'll test if check if that method even works.

**Comment by pierotofy** [comment]
A command line parameter `--load-only "en,fr,it"` would probably be best.
