### ISSUE TITLE
AttributeError: es as frontend target language is not supported.

### ISSUE THREAD

**Issue by sigaloid** [uav4geo/LibreTranslate#54]
```
matt@matt:~/clean/LibreTranslate$ libretranslate 
Traceback (most recent call last):
  File "/home/matt/.local/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/home/matt/.local/lib/python3.8/site-packages/app/main.py", line 35, in main
    app = create_app(args)
  File "/home/matt/.local/lib/python3.8/site-packages/app/app.py", line 77, in create_app
    raise AttributeError(f"{args.frontend_language_target} as frontend target language is not supported.")
```
Only happened once I started editing source to try to add --load-only. I can't get this to go away even after I pip3 remove libretranslate.

**Comment by worldworm** [comment]
Hi,
args.frontend_language_target is set to "es" by [default](https://github.com/uav4geo/LibreTranslate/blob/d4b8d7f8adb7eb387c510d679dda5d20ac9ca348/app/main.py#L24). 
It looks like your installation is missing the spain translation dependencies.

Try setting the "--frontend-language-target" to a language you have installed :)

**Comment by sigaloid** [comment]
I have none installed, previously it would trigger installation when running the command but it doesn't seem to happen again.

**Comment by DevDorrejo** [comment]
hello, this is happening to me with the docker.

**Comment by sigaloid** [comment]
It's got something to do with an old installation I must have cancelled during install, so the files don't exist. Try removing every file related to Argos and Libretranslate. If you have an old laptop, try to replicate the problem on there; for me, it didn't occur. 

Since you're docker, I suppose try stopping and removing it, then making a new docker image

**Comment by DevDorrejo** [comment]
> It's got something to do with an old installation I must have cancelled during install, so the files don't exist. Try removing every file related to Argos and Libretranslate. If you have an old laptop, try to replicate the problem on there; for me, it didn't occur.
> 
> Since you're docker, I suppose try stopping and removing it, then making a new docker image

i am using the default docker run, and yes i remove container and pull again and nothing, same error, and this come inside the docker.

**Comment by sigaloid** [comment]
Hm, is it possible that the model download is not working for some reason?

**Comment by DevDorrejo** [comment]
> Hm, is it possible that the model download is not working for some reason?

good question, and happened on differente environmente, the one that have the container and other 3 that were fresh install of the OS

**Comment by StephenSorriaux** [comment]
Hello,

I came across the same issue using the Docker image. A fresh install of `libretranslate` will actually always trigger this error if models were missing previously because the way the `languages` object (from `app.language`) is reloaded is incorrect. With the Docker container, as no models are actually kept on the disk, it will never start.
Some workarounds:
- mount the path were models will be saved on the host: `docker run -v /tmp/libretranslate/:/root/.local/share/argos-translate -ti --rm -127.0.0.1:5000:5000 libretranslate/libretranslate --load-only en,fr --frontend-language-target fr` for instance: 1st start will fail but 2nd start will be OK since models will be available and that no download will be performed
- build your own Docker image with `with_models=true` as suggested in the README.md file so that no download will be performed at the app startup

**Comment by worldworm** [comment]
Hi everyone,
#68 and #67 is merged.
Does this error still occur or is it fixed now?

Have a great week!

**Comment by StephenSorriaux** [comment]
Thank you, it is fixed on my side.

**Comment by DevDorrejo** [comment]
Getting this on docker.

```
Downloading Turkish -> English (1.1) ...
Downloading English -> Polish (1.1) ...
Traceback (most recent call last):
  File "/usr/local/bin/libretranslate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/app/main.py", line 39, in main
    app = create_app(args)
  File "/usr/local/lib/python3.8/site-packages/app/app.py", line 52, in create_app
    boot(args.load_only)
  File "/usr/local/lib/python3.8/site-packages/app/init.py", line 9, in boot
    check_and_install_models(load_only_lang_codes=load_only)
  File "/usr/local/lib/python3.8/site-packages/app/init.py", line 45, in check_and_install_models
    package.install_from_path(download_path)
  File "/usr/local/lib/python3.8/site-packages/argostranslate/package.py", line 139, in install_from_path
    raise Error('Not a valid Argos Model (must be a zip archive)')
NameError: name 'Error' is not defined
```

**Comment by StephenSorriaux** [comment]
This is not really related to this issue, but the `translate-en_pl-1_1.argosmodel` file has been updated on the GCP storage some hours ago so you should be fine now.

**Comment by PJ-Finlay** [comment]
I've been working on the package index, there was a typo but it should be fixed now.

**Comment by DevDorrejo** [comment]
Thank is all up and working.
