### ISSUE TITLE
Translating a text with arteristics to its sides

### ISSUE THREAD

**Issue by kaname-png** [uav4geo/LibreTranslate#58]
I don't understand why the English translation (I don't know if it happens also with the other languages) of the phrase I put in Spanish appears with the sign `♪` and not with the asterisks that I had put in the Spanish phrase.

![image](https://user-images.githubusercontent.com/56084970/110551921-0fcae080-80fc-11eb-966d-869c75674671.png)

**Comment by PJ-Finlay** [comment]
The sequence to sequence modeling for translations is done with a black box neural network that sometimes does things that don't make any sense. In this case my guess is that the training data included song lyrics with lyrics similar to "Te beso".

A cool feature for LibreTranslate would be to allow users to upload manual translations. This would keep specific issues like this from occurring in future models and, if permissively licensed, could provide a valuable resource to other projects.
