### ISSUE TITLE
Add frontend language default parameter 

### ISSUE THREAD

**Issue by worldworm** [uav4geo/LibreTranslate#6]
Hello there,
first of all: really great work! 

I would love to see a parameter/config/function to set the default language for the frontend. So that you do not always have to set them by hand.

Here I would like to take over the implementation. But first I would like to clarify a few questions with you:

- does this feature make sense at all?
- Implementation via cookie in the frontend so it remembers for each user?
 OR
- Add two cli arguments and integrate them into the frontend via template variables?
 OR
- cli arguments and fetch in frontend via api. e.g. GET /languages/defaults -> { "source": "en", "target": "es"}
 OR
- cli arguments and fetch in frontend via api. e.g. GET /frontend/settings -> { "source": "en", "target": "es", "darkmode": true}
-> here already in view for  https://github.com/EsmailELBoBDev2/LibreTranslate/commit/68ce70cb78a43b94100ab3eca5ddc7fda9d49d8b

I prefer one of the last two options. But I am not sure if this is a bit overloaded, because the main feature of this project is the translation api and the frontend is more of a showcase? (So this feature should rather be included in the project which uses this API...)?

**Comment by PJ-Finlay** [comment]
This has been a requested feature in Argos Translate too, maybe it it can be done in a way that they share the config? Argos Translate mostly does config through environment variables but I don't know if this makes sense for LibreTranslate.

**Comment by worldworm** [comment]
I have already thought about adding a Docker environment mapper to LibreTranslate cli args to make configuration a bit easier.

I have to admit I haven't looked at argos-translate yet.

**Comment by pierotofy** [comment]
> does this feature make sense at all?

Yes!

> I prefer one of the last two options. 

Then go with it. :+1: 

Between the last two I'd edge toward:

> cli arguments and fetch in frontend via api. e.g. GET /frontend/settings

That way concerns are separated. But either way works.

**Comment by worldworm** [comment]
Great!
I'll start my work. Going with the last option GET /frontend/settings.

@EsmailELBoBDev2 fyi


>     * cli arguments and fetch in frontend via api. e.g. GET /frontend/settings -> { "source": "en", "target": "es", "darkmode": true}
>       -> here already in view for  [EsmailELBoBDev2@68ce70c](https://github.com/EsmailELBoBDev2/LibreTranslate/commit/68ce70cb78a43b94100ab3eca5ddc7fda9d49d8b)

**Comment by EsmailELBoBDev2** [comment]
Wait i'm lost, why i'm here? 😂

I mean yes i wanted to add the dark mode but i got hit by my exams (*i fucking hate my school*) and about the post i would say localstroage because cookies are *mostly* bad

**Comment by worldworm** [comment]
@EsmailELBoBDev2 
With https://github.com/uav4geo/LibreTranslate/pull/7 there will be (if it gets approved) a new api endpoint /frontend/settings.
With this cli arguments can easily be passed throug to the frontend so you could hook up/configure your darkmode with this :)

**Comment by EsmailELBoBDev2** [comment]
Darn 😂
how i hookup ? i'm not good in these stuff lol i just want add my dark mode in the template in peace so will be the same?

**Comment by EsmailELBoBDev2** [comment]
@worldworm darn 😂
I'm not good with these stuff so if you could tell me where i would edit then, the same template file or a new file?

**Comment by worldworm** [comment]
@EsmailELBoBDev2 
You could take a look at this [commit](https://github.com/uav4geo/LibreTranslate/commit/72b624db4cff41cfe5c8a333b5548ba8fe882ecb). This is the definition of the two new cli parameters, the api implementation and the call in the frontend. You would basically only need to extend this api to get a boolean into the frontend.
If you want I can support you here or do the implementation completely (then you just have to attach your darkmode to a boolean in the frontend)?

**Comment by EsmailELBoBDev2** [comment]
@worldworm well, i will bookmark the ticket's url and give me some time to read and *try* to understand it and if i got stuck (hopefully not, because it will look awkward) my *step-programmer* i will contact you
