### ISSUE TITLE
Help with accessing on local network

### ISSUE THREAD

**Issue by cbc02009** [uav4geo/LibreTranslate#65]
Very sorry if this is obvious stuff, but I have no experience with web APIs and I could use some help.

I have LibreTranslate running successfully in an LXC container on my home server, and from within the lxc it responds to `curl -X GET "localhost:5000/frontend/settings" -H  "accept: application/json"` fine, but when I try to send a request to it from another computer on the network I get :
```
root@Ubuntu:~$ curl -X GET "10.0.0.33:5000/frontend/settings" -H  "accept: application/json"
curl: (7) Failed to connect to 10.0.0.33 port 5000: Connection refused
```
How can I make LibreTranslate available to my local network (but not the internet)?

I'm sure this isn't a LibreTranslate specific issue, but I wasn't sure where else to ask for help. If anyone could point me towards a guide (or even just what to google to find a guide) I would be super appreciative.

**Comment by cbc02009** [comment]
Solution was to use nginx and proxy_pass as per the documentation here: https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/.

**Comment by pierotofy** [comment]
Glad you figured it out! Thanks for sharing the answer.
