### ISSUE TITLE
Front-end interface is not 100% self-hosted

### ISSUE THREAD

**Issue by D4708** [uav4geo/LibreTranslate#72]
As includes remote dependencies, for example:

```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/prism/1.22.0/prism.min.js"></script>
```

**Comment by pierotofy** [comment]
Pass the `--offline` flag.

**Comment by D4708** [comment]
Thanks for answer, but I have following message on libretranslate --offline

`libretranslate: error: unrecognized arguments: --offline`

**Comment by D4708** [comment]
I've installed LibreTranslate using pip3. So do I need to provide some flags on installation to enable that flag / local libraries?

**Comment by pierotofy** [comment]
Ah, it looks like the PyPI package hasn't been updated in a while.

It should be being updated and published as we speak. So just run `pip3 install -U libretranslate` then try again?

**Comment by D4708** [comment]
Yes, now it works. Thank you!
