### ISSUE TITLE
[BUG] returns some hex encoded char like \u00e1

### ISSUE THREAD

**Issue by graysuit** [uav4geo/LibreTranslate#76]
Respected developers,

**Code:**
```python
import requests

url = 'https://libretranslate.com/translate'
data = {
'source': 'en',
'target': 'es',
'q': 'I live in Pakistan.'
}

x = requests.post(url, data = data)

print(x.text)
```
**Noticed behavior:**
it returns `{"translatedText":"Vivo en Pakist\u00e1n."}`

**Expected behavior:**
I expect it should return `{"translatedText":"Vivo en Pakistán."}`

Currently I'm manually parsing words starting with \u00 and make decode them.

**Comment by graysuit** [comment]
Found a workaround was to replace hex data with hex values.
Please see code:
```python
import requests
import re

url = 'https://libretranslate.com/translate'
data = {
'source': 'en',
'target': 'es',
'q': 'I live in Pakistan.'
}

x = requests.post(url, data = data)
text = re.findall(r'"([^"]*)"', x.text)[1]
index = 0
for char in text:
    if text[index:index-len(text)+4 ] == "\\u00":
        hexdata =  text[index+4: index-len(text)+6 ]
        hexdecoded = ''.join([chr(int(''.join(c), 16)) for c in zip(hexdata[0::2],hexdata[1::2])])
        text = text.replace(text[index: index-len(text)+6 ], str(hexdecoded))
    index += 1
    
print(text)    

#Vivo en Pakistán.
```

**Comment by Philippe-Cholet** [comment]
Thing is it is "jsonified" [here](https://github.com/uav4geo/LibreTranslate/blob/main/app/app.py#L295) meaning `x.text` is a string not a dictionary like it seemed when printing it.

From by idle:
```
>>> x.text
'{"translatedText":"Vivo en Pakist\\u00e1n."}\n'
>>> import json
>>> json.loads(x.text)
{'translatedText': 'Vivo en Pakistán.'}
>>> json.loads(x.text)['translatedText']
'Vivo en Pakistán.'
```
"De-jsonify" it and it should be good.

**Comment by graysuit** [comment]
Nice. It works great.
But I'm not sure what causes the problem ?
Does jsonify fails to encode ?

**Comment by Philippe-Cholet** [comment]
I think it ensures to use only ascii characters by default. I think of this because the keyword argument `ensure_ascii` of `json.dumps` is `True` by default. jsonify probably rely on it. But it is not a problem, json.loads is the right way to get the result.

But `x.json()` instead of `x.text` would probably be way simplier now that I think of it!
