### ISSUE TITLE
libretranslate.com down

### ISSUE THREAD

**Issue by PJ-Finlay** [uav4geo/LibreTranslate#78]
Likely due to traffic from this video:

- https://www.youtube.com/watch?v=1yLSLgeFzYY

**Comment by PJ-Finlay** [comment]
Back up now

**Comment by PJ-Finlay** [comment]
Mirrors:
- https://libretranslate.de/
- https://translate.astian.org/

**Comment by pierotofy** [comment]
At some point I'll have to start setting up some sort of cluster / load balancing.

**Comment by PJ-Finlay** [comment]
I've been thinking about this, I think the best option for now is to try to use some Docker based off the shelf system. 

Long term the ideal is probably some sort of system that can make efficient use of GPUs but the hardware/software for machine learning is changing pretty quickly so this could be tricky. Some sort of serverless Docker container hosting seems like a good choice.

**Comment by graysuit** [comment]
> 
> 
> Mirrors:
> 
>     * https://libretranslate.de/
> 
>     * https://translate.astian.org/

How much limit ? same as 100 r per day ?

**Comment by PJ-Finlay** [comment]
You would have to ask the people running them.

**Comment by graysuit** [comment]
Hi sir,
Thanks a lot.

Can you specify where can I find their maintainers ?
I can't able to from their site.

**Comment by PJ-Finlay** [comment]
[astian.org](https://astian.org) normally has some information about them but I don't know who runs [libretranslate.de](https://libretranslate.de).

**Comment by PJ-Finlay** [comment]
https://translate.fedilab.app/

**Comment by graysuit** [comment]
While talking to owner of [libretranslate.de](http://libretranslate.de)

**Rate limit:** No any limit set yet by author. But may code been set bydefault. 
```python
banned = {} 
active = False  
threshold = -1 


def setup(violations_threshold=100): 
    global active
    global threshold   
    active = True 
    threshold = violations_threshold

    scheduler.add_job(func=clear_banned, trigger="interval", weeks=4)  
```
```bash
while :                                                                                                                                                                                                                                                                          
do                                                                                                                                                                                                                                                                               
curl -X POST "https://libretranslate.de/translate" -H  "accept: application/json" -H  "Content-Type: application/x-www-form-urlencoded" -d "q=Hello%20world&source=en&target=es" 
# spammed the api with this and no ban so i guess its not active. luckily I got a 12 core 4ghz cpu huh?
``` 
Service would be lifetime, free, adfree, anonymous and safe. 
He pays: 300 euros per month for hosting
