### ISSUE TITLE
Limits to use the api on libre translate

### ISSUE THREAD

**Issue by stom79** [uav4geo/LibreTranslate#8]
Hello,

I am really interested to use the API on my project. First, I would like to introduce on a java lib that I created (https://github.com/stom79/mytransl). But, do you agree that I use  your domain for my app (https://github.com/stom79/Fedilab)?

**Comment by pierotofy** [comment]
Hey @stom79 :hand: you're welcome to use it for testing purposes, but if you're going to run an application in production we ask that you run your own server or get in touch https://uav4geo.com/contact to discuss a possible paid plan?

**Comment by stom79** [comment]
A partnership with all credits to project is possible?

**Comment by stom79** [comment]
My main problem is having time to maintain an another server + solution. I can ask people for helping, but if there were a simplest solution, I will be happy.

**Comment by pierotofy** [comment]
There's running costs to keep the server running; credits are nice, but it would be more in the line of setting up a recurring sponsorship / subscription to use the service.

**Comment by stom79** [comment]
Yes, I will try to ask who is interested. I have to reopen an open-collective dedicated to that.

**Comment by stom79** [comment]
My lib is ready to work with LibreTranslate. I updated the README https://github.com/stom79/mytransl#libretranslate
Let me know if something sounds wrong.

**Comment by o-data** [comment]
Hi Ghost, both of your links is error 404, can you check it?
