### ISSUE TITLE
Flood protection

### ISSUE THREAD

**Issue by pierotofy** [uav4geo/LibreTranslate#82]
Welp, that time has arrived where some users have started to abuse the public API at https://libretranslate.com, despite asking people not to do so. This was expected, and probably a good sign :smile: 

The app needs a flood protection system to ban offenders.

I've temporarely disabled translations on the website, unless a user has setup an API key. I'll bring them back once flood protection is in place.

**Comment by PJ-Finlay** [comment]
Also adding some of the mirrors to the README is probably a good idea to direct people that want to regularly use LibreTranslate away from libretranslate.com. They would probably appreciate the traffic too.

- https://libretranslate.de/
- https://translate.astian.org/

**Comment by pierotofy** [comment]
Updated libretranslate.com, so people can now translate again using moderate request limits and repeat offenders will be banned for a month.
