### ISSUE TITLE
Downloading translations on self-hosted instance makes connections to storage.googleapis.com 

### ISSUE THREAD

**Issue by tdeeb** [uav4geo/LibreTranslate#84]
First off, thanks for LibreTranslate! It looks like a fantastic package, and I'm looking to integrate it into my own applications.

Running my own LibreTranslate instance causes it to make connections to `storage.googleapis.com` when downloading translations:
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /argospm/translate-zh_en-1_1.argosmodel (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3321fc9640>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
Followed by:
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /argospm/translate-zh_en-1_1.argosmodel (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3321fc9640>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

I downloaded LibreTranslate through pip and am running it through a terminal on Linux Mint with `libretranslate`. Why is it making requests to Google, and are there any alternative locations to download the translations? Lastly, is there a way to use my own translation models without downloading them from the web each time? Thank you very much!

EDIT: Just noticed https://github.com/argosopentech/argos-translate/issues/7 which looks to be the same issue.

**Comment by PJ-Finlay** [comment]
For some reason you're failing to download a package from the Argos Translate package index (which uses Google Cloud). 

- [Package index web view](https://www.argosopentech.com/argospm/index/)
- [Peer to Peer with IPFS or BitTorrent](https://github.com/argosopentech/argos-translate/blob/master/p2p/README.md)
- [Models section of README](https://github.com/argosopentech/argos-translate#models)

**Comment by mada199122** [comment]
Have you solved?

I have similar issue

```
Cannot update models (normal if you're offline): HTTPSConnectionPool(host='argosopentech.nyc3.digitaloceanspaces.com', port=443): Max retries exceeded with url: /argospm/translate-en_hi-1_1.argosmodel (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd16c67d460>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')
```

But I'm not offline...
I'm using the pre built image from docker hub and my compose is this one

```
  libretranslate:
    image: libretranslate/libretranslate:main
    container_name: "libretranslate"
    volumes:
      - /volume1/docker/Libretranslate:/root/.local/share/argos-translate
    ports:
      - 5000:5000
    restart: unless-stopped
```

**Comment by melroy89** [comment]
Uh.. I get:

```sh
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(URLError(gaierror(-3, 'Temporary failure in name resolution')),)
(RecursionError('maximum recursion depth exceeded while getting the str of an object'),)
(RecursionError('maximum recursion depth exceeded while calling a Python object'),)
(RecursionError('maximum recursion depth exceeded'),)
(RecursionError('maximum recursion depth exceeded while calling a Python object'),)
(RecursionError('maximum recursion depth exceeded while calling a Python object'),)
Traceback (most recent call last):
  File "/app/./venv/bin/libretranslate", line 8, in <module>
Updating language models
Cannot update models (normal if you're offline): maximum recursion depth exceeded while calling a Python object
    sys.exit(main())
             ^^^^^^
  File "/app/venv/lib/python3.11/site-packages/libretranslate/main.py", line 226, in main
    app = create_app(args)
          ^^^^^^^^^^^^^^^^
  File "/app/venv/lib/python3.11/site-packages/libretranslate/app.py", line 191, in create_app
    language_target_fallback = languages[1] if len(languages) >= 2 else languages[0]
                                                                        ~~~~~~~~~^^^
IndexError: list index out of range
```

It doesn't even show me which URL (if at all) is used. I'm using the official docker image btw: `libretranslate/libretranslate`

I'm also connected to the internet. What calls is LibreTranslate trying here!?

**Comment by pierotofy** [comment]
Making the models part of the docker image would make the images huge (and defeat the purpose of LT_LOAD_ONLY).

Just use `./run.sh` to avoid downloading the models every time.

**Comment by melroy89** [comment]
> Just use `./run.sh` to avoid downloading the models every time.

That is not how Docker works. Every time you stop or start a Docker container it will now start downloading the models from scratch (no cache, nothing). This is also the reason the boot time is long. The time you can start using LibreTranslate.

> Making the models part of the docker image would make the images huge (and defeat the purpose of LT_LOAD_ONLY).

That is correct, it would increase the Docker image, with a good reason that each time the Docker container will start it will use the models present in the container (using that Docker tag).
 `LT_LOAD_ONLY` will need to be extended if needed to only load models into its memory (even if the models are present on disk). That shouldn't be the hardest part.

> https://github.com/LibreTranslate/LibreTranslate/blob/main/docker/Dockerfile#L25

Nice, so there is already an optional flag that can be set to build images with models included.

So for the official images you of course should include all models if you would include the models. Then `LT_LOAD_ONLY` of course doesn't need to download it again (and you shouldn't update it either, that is why you also release new Docker images with a tag), but only load the models provided into memory.

This will reduce the load & bandwidth on the https://www.argosopentech.com/ servers enormously. Or they don't care? I mean don't take free bandwidth for granted.

**Comment by pierotofy** [comment]
Try `./run.sh`. 👍

**Comment by melroy89** [comment]
nevermind.
