### ISSUE TITLE
Auto detect source language

### ISSUE THREAD

**Issue by ghost** [uav4geo/LibreTranslate#9]
The api currently requests the source language. But it could be nice to have something like `source=auto`.

**Comment by pierotofy** [comment]
Yep. It's on the roadmap. Also related: https://github.com/argosopentech/argos-translate/issues/9

Consider sponsoring @PJ-Finlay for this feature, or contribute a PR to Argos Translate. Once it's implemented there we can implement it here.

**Comment by vemonet** [comment]
Alternatively, it could be implemented with the `langdetect` library: https://pypi.org/project/langdetect/

```python
from langdetect import detect
detect("War doesn't show who's right, just who's left.")
# Returns 'en'
```

Not sure how accurate it is though

**Comment by pierotofy** [comment]
Oh, interesting. We could add it via this library until support for (better?) detection is available in Argos Translate I suppose. Should be easy to swap it.

If anyone wants to beat me with a pull request for this one.. go for it :)

**Comment by vemonet** [comment]
https://github.com/uav4geo/LibreTranslate/pull/12 :+1:

**Comment by pierotofy** [comment]
This can be closed! Thanks for the PR @vemonet ! :pray:
