### ISSUE TITLE
LibreTranslate Python bindings

### ISSUE THREAD

**Issue by PJ-Finlay** [uav4geo/LibreTranslate#93]
- [LibreTranslate-py](https://github.com/argosopentech/LibreTranslate-py)
- [Argos Translate issue](https://github.com/argosopentech/argos-translate/issues/38)

**Comment by pierotofy** [comment]
w00t! That's awesome. Added a link: https://github.com/uav4geo/LibreTranslate/commit/1c354b65e9d583bb19cbf49d96fdb55e9744ef58
